Md huzaifa 1146
atmeshwar-classic/bookshop pull request #3
Opened 2023-02-06 17:04 UTC by md-huzaifa

Created the Book and Cart pages with functionlaity to add and remove the books to cart and check the total amount

2023-02-07 05:09 UTC, atmeshwar-classic requested changes
Hi @md-huzaifa , Please finish the Cart page, it is incomplete.

2023-02-07 05:12 UTC, atmeshwar-classic commented on package.json
> +    "tailwindcss": "^3.2.4",
Nice touch by adding Tailwind 😄

2023-02-07 05:13 UTC, atmeshwar-classic commented on src/App.tsx
> +    <Router>
Please extract the routes into its own separate file and import them here.
For eg: src/routes/routes.ts

We should maintain the structure of the app regardless of its size.

2023-02-07 05:14 UTC, atmeshwar-classic commented on src/components/NavBar/NavBar.tsx
> +        </li>
No need for Home link as the Books page is the default one.

2023-02-07 05:15 UTC, atmeshwar-classic commented on src/domain/books/BooksPage.tsx
> +      <ToastContainer draggable />
ToastContainer should be at the root of our app in main.tsx.

2023-02-07 05:15 UTC, atmeshwar-classic commented on src/domain/cart/CartPage.tsx
> +      <ToastContainer />
See above.

2023-02-07 05:17 UTC, atmeshwar-classic requested changes
Hi @md-huzaifa Please check the comments I have made.

Also, whenever I click on add to cart button the url adds a '#' in the end. Please look into it as well.

2023-02-07 05:31 UTC, md-huzaifa commented on package.json
> +    "tailwindcss": "^3.2.4",
Thank you

2023-02-08 07:05 UTC, atmeshwar-classic commented on src/routes/routes.tsx
> +      <Route path="/books" element={<BooksPage />} />
Not needed

2023-02-08 07:05 UTC, atmeshwar-classic commented on src/routes/routes.tsx
> +    <>
You can use Routes element here instead of in App.tsx

2023-02-08 07:06 UTC, atmeshwar-classic commented on src/App.tsx
> +  const routes = createRoutes();
Just import Routes like any other React component, no need to do this.

2023-02-08 07:07 UTC, atmeshwar-classic commented on src/routes/routes.tsx
> +const createRoutes = () => {
Just rename it to Routes or Router whatever you like and import it in App like a react component

2023-02-08 10:11 UTC, atmeshwar-classic commented
I am closing this PR as the assessment is complete.
Good job @md-huzaifa . Keep it up!

2023-02-08 10:11 UTC, closed without merging

2023-02-08 11:10 UTC, md-huzaifa commented
Thank you @atmeshwar-classic